# Generated by Django 4.1.7 on 2023-03-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtObjects', '0002_artobject_last_modified_alter_artobject_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='art_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Description', serialize=False, to='ArtObjects.artobject'),
        ),
    ]
