# Generated by Django 4.1.7 on 2023-03-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museum_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_mail', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('halls_number', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Openning_Hours',
            fields=[
                ('day', models.CharField(blank=True, max_length=20, null=True)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('museum_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Openning_Hours', serialize=False, to='InfoMuseum.museum_info')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('museum_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='InfoMuseum.museum_info')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(upload_to='', verbose_name='Imagefile')),
                ('museum_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Media', to='InfoMuseum.museum_info')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_info', models.TextField(blank=True, null=True)),
                ('museum_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Event', to='InfoMuseum.museum_info')),
            ],
        ),
    ]
