# Generated by Django 4.1.7 on 2023-03-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoMuseum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Openning_Hours',
            new_name='Openning_Hour',
        ),
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
