# Generated by Django 4.1.7 on 2023-03-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoMuseum', '0002_rename_openning_hours_openning_hour_media_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Imagefile'),
        ),
    ]
