# Generated by Django 4.1.7 on 2023-03-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfoMuseum', '0003_event_date_alter_media_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_info',
            new_name='event_about',
        ),
    ]
