# Generated by Django 4.1.7 on 2023-03-05 17:38

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoMuseum', '0004_rename_event_info_event_event_about_museum_info_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='museum_info',
            name='contact_phone',
            field=phone_field.models.PhoneField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('museum_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InfoMuseum.museum_info')),
            ],
        ),
    ]
