# Generated by Django 4.1.7 on 2023-03-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InfoMuseum', '0004_rename_event_info_event_event_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='museum_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfoMuseum.museum_info'),
        ),
    ]
