# Generated by Django 4.1.7 on 2023-03-05 17:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('InfoMuseum', '0005_alter_media_media_alter_museum_info_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum_info',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, null=True, region=None),
        ),
    ]
