# Generated by Django 4.1.7 on 2023-03-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InfoMuseum', '0006_alter_museum_info_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='openning_hour',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='museum_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InfoMuseum.museum_info'),
        ),
        migrations.AlterField(
            model_name='openning_hour',
            name='museum_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openning_Hours', to='InfoMuseum.museum_info'),
        ),
    ]
