# Generated by Django 4.1.7 on 2023-03-05 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InfoMuseum', '0007_openning_hour_id_alter_media_museum_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openning_hour',
            name='museum_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='openning_Hours', to='InfoMuseum.museum_info'),
        ),
    ]
