# Generated by Django 4.1.7 on 2023-03-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InfoMuseum', '0008_alter_openning_hour_museum_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openning_hour',
            name='museum_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openning_Hours', to='InfoMuseum.museum_info'),
        ),
    ]
