# Generated by Django 4.1.7 on 2023-03-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoMuseum', '0009_alter_openning_hour_museum_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openning_hour',
            name='day',
            field=models.CharField(blank=True, choices=[('FR', 'Friday'), ('ST', 'Saturday'), ('SN', 'Sunday'), ('MN', 'Monday'), ('TU', 'Tuseday'), ('WE', 'Wednesday'), ('TH', 'Thursday')], default='Friday', max_length=2),
        ),
    ]
