# Generated by Django 4.1.7 on 2023-03-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoMuseum', '0010_alter_openning_hour_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='openning_hour',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openning_hour',
            name='day',
            field=models.CharField(choices=[('FR', 'Friday'), ('ST', 'Saturday'), ('SN', 'Sunday'), ('MN', 'Monday'), ('TU', 'Tuseday'), ('WE', 'Wednesday'), ('TH', 'Thursday')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='openning_hour',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
